import React, { useState, useEffect } from 'react';

const STYLES = ['bottts','micah','adventurer','pixel-art','avataaars'];

function AvatarPlayground({ initialSpec = null, onChange }) {
  const initial = initialSpec || { provider: 'dicebear', style: 'bottts', seed: '' };
  const [style, setStyle] = useState(initial.style || 'bottts');
  const [seed, setSeed] = useState(initial.seed || '');
  const [debouncedSeed, setDebouncedSeed] = useState(seed);
  const [loading, setLoading] = useState(false);

  // Debounce seed updates for preview
  useEffect(() => {
    setLoading(true);
    const t = setTimeout(() => {
      setDebouncedSeed(seed);
      setLoading(false);
    }, 300);
    return () => clearTimeout(t);
  }, [seed, style]);

  useEffect(() => {
    // Notify parent whenever the spec changes
    const spec = { provider: 'dicebear', style, seed };
    onChange && onChange(spec);
  }, [style, seed, onChange]);

  const randomize = () => {
    const s = Math.random().toString(36).slice(2, 10);
    setSeed(s);
  };

  const previewUrl = (st, sd) => {
    const safeSeed = encodeURIComponent(sd || '');
    return `https://api.dicebear.com/6.x/${st}/svg?seed=${safeSeed}`;
  };

  return (
    <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start', flexWrap: 'wrap' }}>
      <div style={{ minWidth: 220 }}>
        <div style={{ display: 'flex', gap: 8, marginBottom: 8, flexWrap: 'wrap' }}>
          {STYLES.map(s => (
            <button key={s} onClick={() => setStyle(s)} type="button" style={{ border: style === s ? '2px solid #37B300' : '1px solid #ddd', padding: 6, borderRadius: 8, background: 'white' }}>
              <img src={previewUrl(s, seed || 'preview')} alt={s} style={{ width: 56, height: 56 }} />
            </button>
          ))}
        </div>

        <div style={{ display: 'flex', gap: 8, marginBottom: 8 }}>
          <input value={seed} onChange={(e) => setSeed(e.target.value)} placeholder="Seed (optional)" style={{ padding: 8, borderRadius: 8, border: '1px solid #ddd', flex: 1 }} />
          <button type="button" onClick={randomize} style={{ padding: '8px 10px', borderRadius: 8, background: '#58CC02', color: 'white', border: 'none' }}>🎲</button>
        </div>

        <div style={{ fontSize: 13, color: '#6B7280' }}>
          Tip: change the seed or click the dice to randomize. Preview is generated by DiceBear's public API.
        </div>
      </div>

      <div style={{ minWidth: 140, textAlign: 'center' }}>
        <div style={{ width: 120, height: 120, borderRadius: 999, overflow: 'hidden', marginBottom: 8, border: '1px solid #eee', display: 'inline-block' }}>
          <img src={previewUrl(style, debouncedSeed || (initial.seed || ''))} alt="avatar preview" style={{ width: '100%', height: '100%', display: 'block' }} />
        </div>
        <div style={{ fontSize: 13, color: '#6B7280' }}>{loading ? 'Updating…' : `${style} · ${debouncedSeed || '(seed)'}`}</div>
      </div>
    </div>
  );
}

export default AvatarPlayground;
