// people.js

const people = [
  {
    id: "u1",
    name: "Lucas",
    emoji: "🕺",
    country: "🇧🇷",
    type: "student",
    desc: "Always down for a dance & deep talk after.",
    interests: ["music", "party", "friends"],
    languages: ["Portuguese", "English", "French"],
    age: 23,
    house: "Maison du Brésil",
    points: 120,
  },
  {
    id: "u2",
    name: "Ana",
    emoji: "🍕",
    country: "🇮🇹",
    type: "cite",
    desc: "Chill foodie who loves spontaneous nights.",
    interests: ["food", "travel", "social events"],
    languages: ["Italian", "English", "Spanish"],
    age: 24,
    house: "Maison de l’Italie",
    points: 95,
  },
  {
    id: "u3",
    name: "Max",
    emoji: "🎤",
    country: "🇩🇪",
    type: "student",
    desc: "Here for Erasmus — got the playlist 🔥.",
    interests: ["music", "DJing", "concerts"],
    languages: ["German", "English"],
    age: 22,
    house: "Maison d’Allemagne",
    points: 180,
  },
  {
    id: "u4",
    name: "François",
    emoji: "📚",
    country: "🇫🇷",
    type: "local",
    desc: "French lit student who likes to sing.",
    interests: ["books", "karaoke", "culture"],
    languages: ["French", "English"],
    age: 25,
    house: "Maison Internationale",
    points: 75,
  },
  {
    id: "u5",
    name: "Emma",
    emoji: "🕯️",
    country: "🇫🇷",
    type: "cite",
    desc: "Loves cozy nights with candles and chill chats.",
    interests: ["outdoors", "picnics", "board games"],
    languages: ["French", "English"],
    age: 23,
    house: "Fondation Deutsch de la Meurthe",
    points: 60,
  },
  {
    id: "u6",
    name: "Leo",
    emoji: "🎸",
    country: "🇪🇸",
    type: "student",
    desc: "Guitar & chill master, always carrying music.",
    interests: ["music", "outdoors", "people"],
    languages: ["Spanish", "English"],
    age: 21,
    house: "Maison d’Espagne",
    points: 110,
  },
  {
    id: "u7",
    name: "Sara",
    emoji: "🧃",
    country: "🇲🇽",
    type: "touristic",
    desc: "Brings weird snacks and fun stories from Mexico.",
    interests: ["food", "friends", "exploring"],
    languages: ["Spanish", "English", "French"],
    age: 24,
    house: "Maison du Mexique",
    points: 140,
  },
  {
    id: "u8",
    name: "Nina",
    emoji: "🎲",
    country: "🇧🇪",
    type: "local",
    desc: "Strategy nerd who’s surprisingly competitive.",
    interests: ["games", "strategy", "tea"],
    languages: ["French", "Dutch", "English"],
    age: 27,
    house: "Maison de Belgique",
    points: 85,
  },
  {
    id: "u9",
    name: "Mina",
    emoji: "🌯",
    country: "🇲🇦",
    type: "popular",
    desc: "Knows every hidden street-food gem in Paris.",
    interests: ["food", "travel", "friends"],
    languages: ["Arabic", "French", "English"],
    age: 26,
    house: "Maison du Maroc",
    points: 160,
  },
  {
    id: "u10",
    name: "Huy",
    emoji: "🍜",
    country: "🇻🇳",
    type: "student",
    desc: "Pho philosopher who always brings good energy.",
    interests: ["food", "philosophy", "music"],
    languages: ["Vietnamese", "English", "French"],
    age: 23,
    house: "Maison de l’Asie du Sud-Est",
    points: 130,
  },
];

export default people;
