// Example users.js for AdminAssign
const users = [
  {
    id: "u1",
    name: "Lucas",
    emoji: "🕺",
    country: "🇧🇷",
    desc: "Always down for a dance & deep talk after.",
    languages: ["portuguese", "english"],
    isBot: true,
  },
  {
    id: "u2",
    name: "Ana",
    emoji: "🍕",
    country: "🇮🇹",
    desc: "Chill foodie who loves spontaneous nights.",
    languages: ["italian", "english"],
    isBot: true,
  },
  {
    id: "u3",
    name: "Max",
    emoji: "🎤",
    country: "🇩🇪",
    desc: "Here for Erasmus — got the playlist 🔥.",
    languages: ["german", "english"],
    isBot: true,
  },
  {
    id: "u4",
    name: "Mitsu",
    username: "Mitsu",
    emoji: "🗼",
    country: "🇫🇷",
    desc: "French from Marseille. Speaks French, Spanish, and English.",
    city: "Marseille",
    languages: ["french", "spanish", "english"],
    isReal: true,
  },
  {
    id: "u5",
    name: "Zine",
    username: "Zine",
    emoji: "🕌",
    country: "🇹🇳",
    desc: "Tunisian. Speaks Arabic, French, and English.",
    city: "Tunis",
    languages: ["arabic", "french", "english"],
    isReal: true,
  },
  {
    id: "admin",
    name: "Admin",
    username: "admin",
    emoji: "🛠️",
    country: "🌍",
    desc: "System administrator",
    languages: ["english", "french"],
    isReal: true,
  },
];

export default users;
